<<<<<<< HEAD
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
=======
"use client"

import { Inter } from 'next/font/google'
import './globals.css'
import { PrivyProvider } from '@privy-io/react-auth';
import { base, baseGoerli, scrollSepolia, scrollTestnet, mainnet, goerli, polygon, polygonMumbai, filecoinCalibration } from '@wagmi/core/chains'
import Navbar from '../components/navbar';

const inter = Inter({ subsets: ["latin"] });


// export const metadata = {
//   title: 'Harveeco',
//   description: 'Generated by create next app',
// }
>>>>>>> origin/design

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
<<<<<<< HEAD
        <Providers>{children}</Providers>
=======
        <PrivyProvider
          appId={process.env.NEXT_PUBLIC_PRIVY_ID}
          onSuccess={(user) => console.log(`User ${user} logged in!`)}
          config={{
            defaultChain: filecoinCalibration,
            supportedChains: [base, baseGoerli, scrollSepolia, scrollTestnet, mainnet, goerli, polygon, polygonMumbai, filecoinCalibration],
            embeddedWallets: {
              createOnLogin: 'users-without-wallets'
            }
          }}
        >
          <Navbar />
          {children}
        </PrivyProvider>
>>>>>>> origin/design
      </body>
    </html>
  );
}
