"use client";
import { config } from "@/chains";
import { Inter } from "next/font/google";
import "./globals.css";
import { PrivyProvider } from "@privy-io/react-auth";
import {
  base,
  baseGoerli,
  scrollSepolia,
  scrollTestnet,
  mainnet,
  goerli,
  polygon,
  polygonMumbai,
  filecoinCalibration,
} from "@wagmi/core/chains";
import Navbar from "../components/navbar";
import { WagmiConfig } from "wagmi";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: 'Harveeco',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiConfig config={config}>
          <PrivyProvider
            appId={"clpxid1p500ijjp0fzu3fy5z0"}
            onSuccess={(user) => console.log(`User ${user} logged in!`)}
            config={{
              defaultChain: filecoinCalibration,
              supportedChains: [
                base,
                baseGoerli,
                scrollSepolia,
                scrollTestnet,
                mainnet,
                goerli,
                polygon,
                polygonMumbai,
                filecoinCalibration,
              ],
              embeddedWallets: {
                createOnLogin: "users-without-wallets",
              },
            }}
          >
            <Navbar />
            {children}
          </PrivyProvider>
        </WagmiConfig>
      </body>
    </html>
  );
}
